key_var <- c("id", 
             "group", 
             "drg", 
             "drg_yield", 
             "age_delivery", 
             "gestation_days", 
             "time_birth", 
             "first_birth", 
             "multiple_birth", 
             "missed_due_date")

complications_delivery <- c("complications_drg", 
                            "shoulder_dystocia", 
                            "frustrated_iol", 
                            "frustrated_vag", 
                            "change_method", 
                            "treatment_related_infections", 
                            "blood_loss", 
                            "manual_placental_abruption", 
                            "protracted_ap", 
                            "premature_placental_abruption", 
                            "weaknes_labor")

complications_maternal <- c("eclampsia", 
                            "fever", 
                            "obstetric_arrest", 
                            "prolonged_inpatient_stay", 
                            "unexpected_readmission", 
                            "maternal_icu_transfer", 
                            "maternal_exhaustion")

complications_fetal <- c("acidosis", 
                         "meconium_aspiration", 
                         "umbilical_cord_prolapse", 
                         "terminal_bradycardia", 
                         "poor_apgar", 
                         "icu_fetal", 
                         "simple_birth_injury", 
                         "decreased_fetal_movement")

pre_existing_risk_fetal <- c("macrosomia", 
                             "polyhydramnios", 
                             "oligohydramnios", 
                             "growth_retardation", 
                             "premature_rupture_membranes", 
                             "green_amniotic_fluid", 
                             "ctg", 
                             "path_doppler", 
                             "induction")

pre_existing_risk_maternal <- c("corona_positive",
                                "corona_symptoms",
                                "incomplete_documentation",
                                "emergency_section",
                                "secondary_section",
                                "desired_section",
                                "allergic_reaction",
                                "anaemia",
                                "hypertension",
                                "hypotension",
                                "preclampsia",
                                "diabetes",
                                "obesity",
                                "nicotine_addiction",
                                "psych_depression",
                                "language_skills",
                                "c_n_section",
                                "birth_position_child",
                                "underlying_maternal_disease",
                                "drug_abuse")

